name: mycli

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'AUTHORS'

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.13'

      - uses: astral-sh/setup-uv@7edac99f961f18b581bbd960d59d049f04c0002f # v6.4.1
        with:
          version: 'latest'

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run mypy
        run: |
          uv run --no-sync --frozen -- python -m mypy --no-pretty --install-types .
